package com.lankheet.iot.datatypes.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * A Measurement is a single information item that is produced by the LNB domotics system. The id
 * field value is generated by the database.
 */
@Entity(name = "measurements")
public class Measurement {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private int id;

    @ManyToOne
    private Sensor sensor;

    @Temporal(value = TemporalType.TIMESTAMP)
    private Date timeStamp;

    private MeasurementType measurementType;

    private double value;

    /**
     * Default constructor required for JPA
     */
    public Measurement() {}

    /**
     * Constructor.
     * 
     * @param sensor Sensor as stored in database
     * @param timeStamp The time of occurrence
     * @param type Type of measurement as known in database
     * @param value The value of the measurement
     */
    public Measurement(Sensor sensor, Date timeStamp, MeasurementType measurementType, double value) {
        this.sensor = sensor;
        this.measurementType = measurementType;
        this.timeStamp = timeStamp;
        this.value = value;
    }
    
    public int getId() {
        return id;
    }

    public Sensor getSensor() {
        return sensor;
    }

    public MeasurementType getMeasurementType() {
        return measurementType;
    }

    public void setMeasurementType(MeasurementType measurementType) {
        this.measurementType = measurementType;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public double getValue() {
        return value;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Measurement [id=" + id + ", sensor=" + sensor + ", timeStamp=" + timeStamp + ", measurementType="
                + measurementType + ", value=" + value + "]";
    }
}
