-- This script was generated by Intellij database plugin.
create table PERMISSIONS
(
    ID              INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    NAME            VARCHAR(45) not null,
    PERMISSIONFLAGS INTEGER     not null,
    primary key (ID)
);

create table SITES
(
    ID          BIGINT default GENERATED_BY_DEFAULT generated always as identity,
    DESCRIPTION VARCHAR(255),
    DTCREATED   TIMESTAMP,
    NAME        VARCHAR(255),
    primary key (ID)
);

create table MQTT_CONFIG
(
    ID            INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    CLIENTID      DECIMAL(31, 2),
    URL           VARCHAR(255),
    USERID        DECIMAL(31, 2),
    SITEENTITY_ID BIGINT,
    primary key (ID),
    constraint FKOJMNN90BUXLO5MPAW0JL5FVUU
        foreign key (SITEENTITY_ID) references SITES
);

create table DEVICES
(
    ID              BIGINT default GENERATED_BY_DEFAULT generated always as identity,
    FIRMWAREVERSION VARCHAR(255),
    HARDWAREVERSION VARCHAR(255),
    MACADDRESS      VARCHAR(255),
    MANUFACTURERID  VARCHAR(255),
    MODELID         VARCHAR(255),
    MQTTCONFIG_ID   INTEGER,
    SITEENTITY_ID   BIGINT,
    primary key (ID),
    constraint FK8RTCSCPEQ0B5OXSR7CO9QPEU0
        foreign key (MQTTCONFIG_ID) references MQTT_CONFIG,
    constraint FKRVMRNCR23YT3MB20V7LNKWDK
        foreign key (SITEENTITY_ID) references SITES
);

create table ACTUATORS
(
    ID              INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    DESCRIPTION     VARCHAR(255),
    MQTTTOPIC       VARCHAR(255),
    NAME            VARCHAR(255),
    DEVICEENTITY_ID BIGINT,
    primary key (ID),
    constraint FK5QBITKMMDHYA9DT9KYM7P5KQD
        foreign key (DEVICEENTITY_ID) references DEVICES
);

create table MQTT_TOPICS
(
    ID                  INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    PATH                VARCHAR(255),
    MQTTCONFIGENTITY_ID INTEGER,
    primary key (ID),
    constraint FK58NEVYC05DSXUEMYYIN75PHLI
        foreign key (MQTTCONFIGENTITY_ID) references MQTT_CONFIG
);

create table SENSORS
(
    ID              INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    DESCRIPTION     VARCHAR(255),
    MQTTPATH        VARCHAR(255),
    MQTTTOPIC       VARCHAR(255),
    NAME            VARCHAR(255),
    SENSORTYPEVALUE INTEGER not null,
    DEVICEENTITY_ID BIGINT,
    primary key (ID),
    constraint FKKSQCBTXXTT87BA7Q42WRE0E5D
        foreign key (DEVICEENTITY_ID) references DEVICES
);

create table DOMIOT_PARAMETERS
(
    ID                BIGINT default GENERATED_BY_DEFAULT generated always as identity,
    ACTUATORENTITY_ID INTEGER,
    DEVICEENTITY_ID   BIGINT,
    SENSORENTITY_ID   INTEGER,
    primary key (ID),
    constraint FK3DO0EEAA4GX9P6SNL57LJJDF7
        foreign key (SENSORENTITY_ID) references SENSORS,
    constraint FK3M2U0BBO5G0JF0DG820Y9BG9E
        foreign key (ACTUATORENTITY_ID) references ACTUATORS,
    constraint FKSV7D9BBM5MRVWGX196LNGIAYC
        foreign key (DEVICEENTITY_ID) references DEVICES
);

create table SENSORVALUES
(
    ID              INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    MEASUREMENTTYPE INTEGER,
    TIMESTAMP       TIMESTAMP,
    VALUE           DOUBLE not null,
    SENSORENTITY_ID INTEGER,
    primary key (ID),
    constraint FK3TQ6I6SBETJCYDVNFC3DOQF9I
        foreign key (SENSORENTITY_ID) references SENSORS
);

create table USERS
(
    ID            INTEGER default GENERATED_BY_DEFAULT generated always as identity,
    EMAIL         VARCHAR(45) not null,
    FIRSTNAME     VARCHAR(255),
    LASTNAME      VARCHAR(255),
    PASSWORD      VARCHAR(64) not null,
    USERNAME      VARCHAR(45) not null,
    SITEENTITY_ID BIGINT,
    primary key (ID),
    unique (EMAIL),
    unique (USERNAME),
    constraint FK5AP13NQOCJDGR77MTH91K7KW1
        foreign key (SITEENTITY_ID) references SITES
);

create table USERS_PERMISSIONS
(
    USERENTITY_ID  INTEGER not null,
    PERMISSIONS_ID INTEGER not null,
    constraint FKBEHN7JLD0V03JHYJNTNWSN8R7
        foreign key (PERMISSIONS_ID) references PERMISSIONS,
    constraint FKMIYSAWAK6JCWC4C4CRKAUA1R4
        foreign key (USERENTITY_ID) references USERS
);

