package com.lankheet.iot.datatypes;

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A Measurement is a single information item that is produced by the LNB
 * domotics system. The id field value is generated by the database. The sensorId is
 * retrieved manually from the web service (until an automated system is
 * created).
 */
@Entity
@Table(name = "measurements")
public class Measurement {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	@JsonProperty
	@JoinColumn(name = "Sensor.id")
	private int sensorId;

	@JsonProperty
	@Temporal(value = TemporalType.TIMESTAMP)
	private LocalDateTime timeStamp;

	@JsonProperty
	@Enumerated(EnumType.ORDINAL)
	private MeasurementType type;

	@JsonProperty
	private double value;

	/**
	 * Default constructor required for JPA
	 */
	public Measurement() {
	}

	@JsonCreator
	public Measurement(@JsonProperty("sensorId") int sensorId, @JsonProperty("timeStamp") LocalDateTime timeStamp,
			@JsonProperty("type") MeasurementType type, @JsonProperty("value") double value) {
		this.sensorId = sensorId;
		this.type = type;
		this.timeStamp = timeStamp;
		this.value = value;
	}

	public int getSensorId() {
		return sensorId;
	}

	public MeasurementType getType() {
		return type;
	}

	public LocalDateTime getTimeStamp() {
		return timeStamp;
	}

	public double getValue() {
		return value;
	}

	@Override
	public String toString() {
		return "Measurement [sensorId=" + sensorId + ", timeStamp=" + timeStamp + ", type=" + type + ", value=" + value
				+ "]";
	}
}
