package org.lankheet.domiot.entities;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.lankheet.domiot.entities.conversion.MeasurementTypeConverter;

/**
 * A Measurement is a single information item that is produced by the LNB domotics system. The id field value is generated by
 * the database.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "sensor_values", schema = "domiot")
public class SensorValueEntity {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", updatable = false, nullable = false)
  private int id;

  @ManyToOne(cascade = {CascadeType.ALL})
  private SensorEntity sensorEntity;

  @Temporal(value = TemporalType.TIMESTAMP)
  private Date timeStamp;

  @Convert(converter = MeasurementTypeConverter.class)
  private MeasurementType measurementType;

  private double value;
}
